name: Release

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: Branch to release
        required: true
        default: staging
        type: string

jobs:
  initialize:
    name: Initialize
    runs-on: ubuntu-20.04
    outputs:
      releasing_version: ${{ steps.releasing_version.outputs.releasing_version }}      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:          
          ref: ${{ github.event.inputs.release_branch }}      
      
      - name: Determine releasing version        
        id: releasing_version
        run: |
          CURRENT_VERSION=$(awk '/## NEXT/,/url/' config.toml | grep -o '\"v.*\"' | tr -d '\"' | xargs)

          # The following command adds the .z part of the version          
          RAW_VERSION=$(echo "$CURRENT_VERSION.0")
          
          echo "::set-output name=releasing_version::$(./.github/workflows/util/bump.py minor $RAW_VERSION)"          
      
      - name: Log information
        run: |
          echo "Releasing version: ${{ steps.releasing_version.outputs.releasing_version }}"

  release:
    name: Release
    runs-on: ubuntu-20.04
    needs: [initialize]
    env:      
      RELEASING_VERSION: ${{ needs.initialize.outputs.releasing_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:          
          ref: ${{ github.event.inputs.release_branch }}    
          fetch-depth: 0 

      - name: Configure git
        run: |
          git config user.email 'kiali-dev@googlegroups.com'
          
          git config user.name 'kiali-bot'
        
      - name: Create release
        run: |          
          echo "Resolved current website version: $RELEASING_VERSION"
          
          ./scripts/release.sh -cv $RELEASING_VERSION -rn origin -gd true
